### ISSUE TITLE
SES Reports - Frequency has only one value allowed

### ISSUE THREAD

**Issue by maciekpapiez** [awslabs/aws-support-tools#60]
The CloudFormation stack declares an input parameter `Frequency`, but it has only one value allowed and hence, cannot be changed.

```
  Frequency:
    Type: String
    Default: "cron(00 23 * * ? *)"
    AllowedValues: 
      - "cron(00 23 * * ? *)"
    Description: "cron(00 23 * * ? *) = Once a day at 23h00" 
```
